### ISSUE TITLE
Can we as NeoMutt Organization use your colorscheme?

### ISSUE THREAD

**Issue by toogley** [KKPMW/moonshine-mutt#1]
Hello.

You haven't uploaded a LICENSE file to your project, so i'll ask to be sure: We as [NeoMutt Project](https://github.com/neomut) would like to include your colorscheme into our sources. Do you mind doing so?

regards,
toogley / Tobias Angele

**Comment by KKPMW** [comment]
Hello,

Of course you can use it! I never bothered uploading a license because I thought no-one will care about this. So if this message is enough - please go ahead and use it. Otherwise I can upload some license file that is most suitable for you.

kind regards,
Karolis K.

**Comment by KKPMW** [comment]
Also I have to add that I took the regular expressions for email and web from here: http://www.strcat.de/dotfiles/mutt.color without actually checking the license. Without asking honestly - I never thought license could apply to a config file. But if it does - might be important to get permission from the author as well.

**Comment by toogley** [comment]
@KKPMW thank you very much. However, i don't know if we need a license. But i think it can't harm - therefore i am happy if you upload a license file.

**Comment by toogley** [comment]
@KKPMW you are of course welcome to join the Neomutt team if you want.

**Comment by KKPMW** [comment]
Hello again,

I added a license.md file for GNU general public license v3. Hope it suits your needs, if not I can change that to anything you want really.

Also thank you for the invitation to the Neomutt team - unfortunately I don't think I can bring anything valuable to the table - I don't even program in C. But I really admire the project and the great work you guys are doing.

**Comment by toogley** [comment]
@KKPMW Thank you - both for adding the GNU license and the compliment.

Regarding the invitation: [It doesn't matter how much you know](https://www.neomutt.org/help) - especially how good you can program in C. 
1. there are plenty of things you can do without knowing C, for instance translating mutt, improving our documentation, writing scripts, testing, packaging, etc. pp.

2. If you're motivated, we can help you learn C programming. For instance, we have set up some [easy coding tasks](https://www.neomutt.org/2016/10/07/news) to get you familiar with the code.

**If you want to help, you'll be valuable for our team :)**
